apiVersion: apps/v1
kind: Deployment
metadata: 
  name: vvk17-go-base
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vvk17-go-base
  template:
    metadata:
      labels:
        app: vvk17-go-base
    spec:
      containers:
      - name: vvk17-go-base
        image: vvk17/vvk17-go-base:0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1

